require 'spec_helper'

describe Revue::Diff do
  context "A diff with the same filename" do
    let(:diff) { FactoryGirl.build(:simple_diff) }

    it "should return the same name for original and modified files" do
      diff.original_filename.should == diff.modified_filename
    end

    describe "#original_filename" do
      it "should parse the filename from the original file line" do
        diff.original_filename.should == "Original"
      end
      it "returns the modified filename if the original name is '/dev/null'" do
        diff = FactoryGirl.build(:diff_with_null_original_filename)
        diff.original_filename.should == diff.modified_filename
      end
    end
  end

  context "A diff with a modified file name" do
    let(:diff) { FactoryGirl.build(:diff_with_modified_filename) }

    it "should return different names for original and modified files" do
      diff.modified_filename.should_not == diff.original_filename
    end

    describe "#modified_filename" do
      it "should return the modified file name" do
        diff.modified_filename.should == "Modified"
      end
    end
  end

  context "A diff generated by git" do
    let(:diff) { FactoryGirl.build(:git_diff) }

    describe "#original_filename" do
      it "returns the correct filename" do
        diff.original_filename.should == "app/controllers/api/v1/code_reviews_controller.rb"
      end
      it "strips out the a/ from the filename" do
        diff.original_filename[0..1].should_not == "a/"
      end
    end

    describe "#modified_filename" do
      it "strips out the b/ from the filename" do
        diff.modified_filename[0..1].should_not == "b/"
      end
    end
  end

  describe "#original_revision" do
    context "A diff with a timestamp revision" do
      it "Displays the timestamp in the correct format" do
        diff = FactoryGirl.build(:simple_diff)
        diff.original_revision.should == "2013-03-23 21:06:27.000000000 +0000"
      end
    end
    context "A diff with a version control revision" do
      it "Displays the revision number" do
        diff = FactoryGirl.build(:diff_with_commit_revision)
        diff.original_revision.should == "(revision 815)"
      end
    end
  end

  describe "#modified_revision" do
    context "A diff with a timestamp revision" do
      it "Displays the timestamp in the correct format" do
        diff = FactoryGirl.build(:simple_diff)
        diff.modified_revision.should == "2013-03-23 21:06:48.000000000 +0000"
      end
    end
    context "A diff with a version control revision" do
      it "Displays the revision number" do
        diff = FactoryGirl.build(:diff_with_commit_revision)
        diff.modified_revision.should == "(working copy)"
      end
    end
  end

  describe "#number_of_deleted_lines" do
    it "returns the number of deleted lines" do
      diff = FactoryGirl.build(:simple_diff)
      diff.number_of_deleted_lines.should == 3
    end
  end

  describe "#number_of_added_lines" do
    it "returns the number of added lines" do
      diff = FactoryGirl.build(:simple_diff)
      diff.number_of_added_lines.should == 2
    end
  end

  describe "#number_of_modified_lines" do
    it "returns the total number of additions and deletions" do
      diff = FactoryGirl.build(:simple_diff)
      diff.number_of_modified_lines.should == 5
    end
  end

  describe "#proportion_of_deleted_lines" do
    context "a new file" do
      it "returns 0" do
        diff = FactoryGirl.build(:new_file_diff)
        diff.proportion_of_deleted_lines.should == 0
      end
    end
    context "a removed file" do
      it "returns 100" do
        diff = FactoryGirl.build(:removed_file_diff)
        diff.proportion_of_deleted_lines.should == 100
      end
    end
    context "a file with equal added and deleted lines" do
      it "returns 50" do
        diff = FactoryGirl.build(:diff_with_commit_revision)
        diff.proportion_of_deleted_lines.should == 50
      end
    end
    context "a file with 75% deleted lines" do
      it "returns 75" do
        diff = FactoryGirl.build(:diff_with_modified_filename)
        diff.proportion_of_deleted_lines.should == 75
      end
    end

  end

  describe "#chunks" do
    context "A diff with 1 chunk" do
      it "returns a single chunk" do
        diff = FactoryGirl.build :simple_diff
        diff.chunks.length.should == 1
      end
    end
    context "A diff with 2 chunks" do
      it "returns 2 chunks" do
        diff = FactoryGirl.build :two_chunk_diff
        diff.chunks.length.should == 2
      end
    end
  end
end